server:
  port: 6666

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: unique-subha-svc1 # unique id
          uri: lb://subha-svc1 # should match with svc name
          predicates:
            - Path=/subha-svc1/**

        - id: unique-subha-svc2
          uri: lb://subha-svc2
          predicates:
            - Path=/subha-svc2/**

