server:
  port: 6666

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: unique-subha-svc1 # unique id
          uri: lb://subha-svc1 # should match with svc name
          predicates:
            - Path=/subha-svc1/**
          filters:
            - RewritePath=/subha-svc1/(?<segment>.*), /${segment}
            
        - id: unique-subha-svc1=2 # unique id
          uri: lb://subha-svc2 # should match with svc name
          predicates:
            - Path=/subha-svc2/**
          filters:
            - RewritePath=/subha-svc2/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: subhaSvc1CircuitBreaker
                fallbackUri: forward:/fallback/subhaSvc1Fallback
      default-filters: # security filters go there
        - SecureHeaders
        - AccessTokenSecurityFilter
        - TenantAvailabilityFilter
        - LoggingFilter
        - GlobalRetryGatewayFilter

resilience4j:
  circuitbreaker:
    instances:
      subhaSvc1CircuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
      
